name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    - '**.rst'
    - '**.txt'
    tags-ignore:
    - 'v**' # Don't run CI tests on release tags

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint
      uses: lgeiger/black-action@master
      with:
        args: '--check --diff .'
    - name: Tests
      run: |
        pip install --use-feature=2020-resolver -r requirements.dev.txt -e .
        pytest -x -s -vvv -k 'not runstatus' tests/
        # Runstatus-related tests disabled until api.runstatus.com supports IAM API keys
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
