name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint
      uses: lgeiger/black-action@master
      with:
        args: '--check --diff .'
    - name: Tests
      run: |
        pip install -r requirements.dev.txt -e .
        pytest -x -s -vvv tests/
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
